 ---
- name: Install Apache Tomcat 9 on Ubuntu
  hosts: all
  become: yes
  vars:
    tomcat_version: 9.0.93
    tomcat_install_dir: /opt/tomcat
    tomcat_user: tomcat
    tomcat_group: tomcat
    java_home: /usr/lib/jvm/java-17-openjdk-amd64   # Correct JDK path

  tasks:

  - name: Update apt repo and install dependencies
    apt:
      name:
        - default-jdk
        - wget
        - curl
        - tar
      state: present
      update_cache: yes

  - name: Create tomcat group
    group:
      name: "{{ tomcat_group }}"
      state: present

  - name: Create tomcat user
    user:
      name: "{{ tomcat_user }}"
      group: "{{ tomcat_group }}"
      shell: /bin/false
      create_home: no

  - name: Download Tomcat 9
    get_url:
      url: "https://dlcdn.apache.org/tomcat/tomcat-9/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"
      dest: /tmp/apache-tomcat-9.tar.gz
      mode: '0644'

  - name: Create Tomcat directory
    file:
      path: "{{ tomcat_install_dir }}"
      state: directory

  - name: Extract Tomcat archive
    unarchive:
      src: /tmp/apache-tomcat-9.tar.gz
      dest: "{{ tomcat_install_dir }}"
      remote_src: yes
      extra_opts: [--strip-components=1]

  - name: Change ownership of Tomcat directory
    file:
      path: "{{ tomcat_install_dir }}"
      state: directory
      owner: "{{ tomcat_user }}"
      group: "{{ tomcat_group }}"
      recurse: yes

  - name: Create systemd service file for Tomcat
    copy:
      dest: /etc/systemd/system/tomcat.service
      content: |
        [Unit]
        Description=Apache Tomcat 9
        After=network.target

        [Service]
        Type=forking

        Environment="JAVA_HOME={{ java_home }}"
        Environment="CATALINA_PID={{ tomcat_install_dir }}/temp/tomcat.pid"
        Environment="CATALINA_HOME={{ tomcat_install_dir }}"
        Environment="CATALINA_BASE={{ tomcat_install_dir }}"
        Environment="CATALINA_OPTS=-Xms512M -Xmx1024M -server -XX:+UseParallelGC"
        Environment="JAVA_OPTS=-Djava.awt.headless=true -Djava.security.egd=file:/dev/./urandom"

        ExecStart={{ tomcat_install_dir }}/bin/startup.sh
        ExecStop={{ tomcat_install_dir }}/bin/shutdown.sh

        User={{ tomcat_user }}
        Group={{ tomcat_group }}
        UMask=0007
        RestartSec=10
        Restart=always

        [Install]
        WantedBy=multi-user.target

  - name: Reload systemd daemon
    command: systemctl daemon-reload

  - name: Enable and start Tomcat
    systemd:
      name: tomcat
      enabled: yes
      state: started
